import { HandCoins, ArrowRight } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useLang } from "@/i18n/I18nContext";

// A block of the article. `h` = section heading, `p` = paragraph,
// `ul` = bullet list, `ol` = numbered steps.
type Block = { h: string } | { p: string } | { ul: string[] } | { ol: string[] };

interface Article {
  title: string;
  subtitle: string;
  blocks: Block[];
}

// ── Slovenian (source) ──
const SL: Article = {
  title: "Brezpogojno financiranje v Lana ekosistemu",
  subtitle: "Skupnost, ki človeku zaupa",
  blocks: [
    { p: "Brezpogojno financiranje je nov način skupnostnega financiranja znotraj Lana ekosistema." },
    { p: "Članom skupnosti omogoča, da prejmejo podporo v trenutkih osebne stiske, pri prehodu v bolj naraven način življenja ali pri ustvarjanju projektov, izdelkov in storitev za skupno dobro." },
    { p: "Financiranje lahko zagotovijo:" },
    { ul: [
      "centralni sklad Unconditional Financing,",
      "posamezni člani Lana skupnosti,",
      "ali centralni sklad in člani skupnosti skupaj.",
    ] },
    { p: "Brezpogojno financiranje ne temelji na klasični bančni presoji, premoženju, zaposlitvi, zavarovanju, obrestih ali dokazovanju kreditne sposobnosti." },
    { p: "Njegov temelj so:" },
    { ul: [
      "zaupanje,",
      "transparentnost,",
      "aktivna vključenost v skupnost,",
      "samoodgovornost,",
      "medsebojna podpora,",
      "ter pripravljenost, da se prejeta vrednost vrne v skupni tok, kadar je to mogoče.",
    ] },

    { h: "Brezpogojno ne pomeni brez samoodgovornosti." },
    { p: "Pomeni, da človeka ne pogojujemo z njegovo preteklostjo, finančnim položajem ali premoženjem. Gledamo njegovo resnično prisotnost, njegov odnos do skupnosti, namen financiranja ter smer, v katero želi s podporo skupnosti stopiti." },

    { h: "Financiranje je izraženo v FIAT valuti" },
    { p: "Vsako brezpogojno financiranje je izraženo in vodeno v izbrani FIAT valuti." },
    { p: "Prosilec ob oddaji zahtevka:" },
    { ul: [
      "vnese želeni znesek,",
      "izbere FIAT valuto financiranja,",
      "ter v tej valuti predstavi namen in pričakovani obseg financiranja.",
    ] },
    { p: "To so lahko na primer:" },
    { ul: ["EUR,", "USD,", "GBP,", "ali druge valute, ki jih podpira Lana ekosistem."] },
    { p: "Če je financiranje ustvarjeno v evrih, se v evrih vodijo:" },
    { ul: [
      "želeni znesek,",
      "vrednost posameznih prispevkov,",
      "skupna financirana vrednost,",
      "že vrnjeni znesek,",
      "preostala odprta vrednost,",
      "obračunane provizije,",
      "ter neto prejeta in izplačana vrednost.",
    ] },
    { p: "Vsa dejanska plačila se izvajajo v LANI." },
    { p: "Sistem ob vsakem prispevku ali vračilu samodejno izračuna, koliko LANE predstavlja izbrani FIAT znesek glede na menjalno razmerje, ki velja v trenutku transakcije." },
    { p: "Uporabniki zato vedno razmišljajo in komunicirajo v FIAT zneskih, LANA pa predstavlja sredstvo, s katerim se vrednost dejansko prenese." },

    { h: "Kdo lahko zaprosi za brezpogojno financiranje?" },
    { p: "Zahtevek za novo brezpogojno financiranje lahko odda uporabnik, ki je član Lana8Wonder najmanj štiri zaključene Splite." },
    { p: "Ta pogoj zagotavlja, da se človek pred prošnjo za financiranje najprej vključi v Lana ekosistem, spozna njegovo delovanje ter razvije odnos s skupnostjo." },
    { p: "Brezpogojno financiranje ni namenjeno ljudem, ki se sistemu pridružijo samo zato, da bi takoj zaprosili za sredstva." },
    { p: "Namenjeno je aktivnim članom, ki so del skupnosti ter želijo s podporo drugih:" },
    { ul: [
      "premostiti osebno stisko,",
      "narediti pomemben življenjski premik,",
      "ali ustvariti nekaj, kar bo služilo skupnemu dobremu.",
    ] },

    { h: "Tri vrste brezpogojnega financiranja" },
    { p: "Vsak prosilec ob oddaji zahtevka izbere eno izmed treh vrst financiranja." },

    { h: "1. Financiranje za reševanje osebne stiske" },
    { p: "Ta oblika financiranja je namenjena človeku, ki se je znašel v osebni, življenjski ali finančni situaciji, v kateri potrebuje pomoč skupnosti." },
    { p: "Sredstva lahko potrebuje na primer za:" },
    { ul: [
      "poravnavo nujnih obveznosti,",
      "ureditev bivanja,",
      "zdravljenje ali regeneracijo,",
      "selitev,",
      "izobraževanje,",
      "pomoč družini,",
      "ponovno vzpostavitev osebne stabilnosti,",
      "ali drugo iskreno življenjsko potrebo.",
    ] },
    { p: "Človeku ni treba dokazovati, da bo s prejetimi sredstvi ustvaril dobiček." },
    { p: "Namen financiranja je, da mu skupnost pomaga ponovno vzpostaviti ravnovesje, zadihati in narediti naslednji korak." },

    { h: "2. Financiranje prehoda v bolj naraven življenjski slog" },
    { p: "Ta oblika financiranja je namenjena ljudem, ki želijo narediti konkreten premik proti bolj naravnemu, zdravemu, kakovostnemu in samostojnemu načinu življenja." },
    { p: "Sredstva se lahko uporabijo na primer za:" },
    { ul: [
      "preselitev v bolj naravno okolje,",
      "ureditev doma ali zemljišča,",
      "pridelovanje lastne hrane,",
      "nakup opreme za večjo samooskrbo,",
      "vzpostavitev bolj zdravega življenjskega okolja,",
      "zmanjšanje odvisnosti od obstoječega sistema,",
      "ali drugo spremembo, ki človeka približa naravi in večji kakovosti življenja.",
    ] },
    { p: "S tem skupnost ne podpira samo posameznika, temveč tudi širši prehod v bolj naraven, kakovosten in uravnotežen način življenja." },

    { h: "3. Financiranje projekta, namenjenega skupnemu dobremu" },
    { p: "Ta oblika financiranja je namenjena razvoju projekta, izdelka, storitve ali organizacije, ki ustvarja nekaj dobrega za ljudi, skupnost, živali, naravo in življenje kot celoto." },
    { p: "Ne gre za klasično poslovno financiranje, katerega glavni namen so povečevanje dobička, širjenje podjetja ali ustvarjanje novih klasičnih delovnih mest." },
    { p: "Gre za podporo projektom, ki nastajajo v duhu Ekonomije obilja." },
    { p: "Takšni projekti lahko ustvarjajo prihodke in so lahko poslovno uspešni, vendar denar ni njihov končni namen." },
    { p: "Denar je sredstvo, ki jim omogoča, da ustvarjajo kakovostnejše izdelke in storitve, razvijajo skupnost ter prispevajo k skupnemu dobremu." },
    { p: "Podprti projekti morajo prispevati k:" },
    { ul: [
      "večji kakovosti življenja,",
      "zdravju in dobremu počutju ljudi,",
      "širjenju Lana skupnosti,",
      "ustvarjanju kakovostnejših izdelkov in storitev,",
      "povezovanju in sodelovanju med ljudmi,",
      "spoštovanju človeka in njegovega dostojanstva,",
      "varovanju narave, živali in planeta,",
      "ohranjanju ter negovanju vsega živega,",
      "razvoju bolj naravne in odgovorne ekonomije,",
      "ali navdihovanju drugih, da tudi sami začnejo ustvarjati za skupno dobro.",
    ] },
    { p: "Temeljni namen takšnega projekta ni samo prodati izdelek ali storitev." },
    { p: "Njegov namen je ustvariti nekaj, kar izboljšuje življenje, dviguje kakovost, varuje naravno ravnovesje ter prispeva k lepšemu in bolj človeškemu svetu." },

    { h: "Ekonomija obilja" },
    { p: "Ekonomija obilja predstavlja prehod iz ekonomije pomanjkanja, tekmovanja in ustvarjanja predvsem zaradi dobička v ekonomijo, ki v središče postavlja življenje." },
    { p: "V Ekonomiji obilja ne ustvarjamo čim več izdelkov in storitev samo zato, da bi povečali potrošnjo." },
    { p: "Ustvarjamo bolje, kakovostneje in na višjem nivoju." },
    { p: "Ustvarjamo izdelke in storitve, ki:" },
    { ul: [
      "imajo resnično vrednost za človeka,",
      "izboljšujejo kakovost življenja,",
      "so ustvarjeni s skrbjo, znanjem in ljubeznijo,",
      "spoštujejo ljudi, ki jih ustvarjajo in uporabljajo,",
      "ne uničujejo narave zaradi kratkoročnega dobička,",
      "ne izkoriščajo živali ali drugih živih bitij,",
      "so kakovostni, trajni in odgovorno izdelani,",
      "ter za seboj puščajo več življenja, ne manj.",
    ] },
    { p: "Ekonomija obilja pomeni, da si kot skupnost dovolimo ustvarjati najboljše, kar zmoremo." },
    { p: "Ne iščemo najcenejše rešitve ne glede na posledice, temveč rešitev, ki je dobra za človeka, skupnost, naravo in prihodnje generacije." },
    { p: "V takšni ekonomiji uspeh projekta ni določen samo s količino prodaje ali višino dobička." },
    { p: "Uspeh pomeni tudi:" },
    { ul: [
      "koliko dobrega je projekt ustvaril,",
      "koliko ljudi je podprl ali navdihnil,",
      "kako je izboljšal kakovost življenja,",
      "kako odgovorno je ravnal z naravo in viri,",
      "ter ali je s svojim obstojem prispeval k ohranjanju vsega živega.",
    ] },
    { p: "Brezpogojno financiranje projektov za skupno dobro je zato namenjeno ljudem, ki ne želijo ustvarjati samo zase." },
    { p: "Namenjeno je tistim, ki želijo skozi svoje delo, izdelke in storitve ustvarjati obilje, ki se širi med ljudi in hkrati spoštuje življenje v vseh njegovih oblikah." },

    { h: "Obvezen predhodni crowdfunding" },
    { p: "Pri financiranju projekta, namenjenega skupnemu dobremu, mora biti pred oddajo zahtevka izveden najmanj en crowdfunding projekt, povezan z isto idejo ali njenim razvojem." },
    { p: "Prosilec mora v vlogi jasno navesti:" },
    { ul: [
      "na kateri crowdfunding projekt ali projekte se financiranje nanaša,",
      "kaj je bilo s crowdfundingom že ustvarjeno,",
      "koliko podpore je projekt že prejel,",
      "v kateri razvojni fazi je projekt,",
      "kako projekt prispeva k Ekonomiji obilja,",
      "kako njegovi izdelki ali storitve služijo skupnemu dobremu,",
      "kako projekt spoštuje in ohranja vse živo,",
      "ter zakaj za naslednji korak potrebuje brezpogojno financiranje.",
    ] },
    { p: "Crowdfunding predstavlja prvi korak, skozi katerega se ideja predstavi skupnosti, pridobi začetno podporo in začne razvijati." },
    { p: "Brezpogojno financiranje predstavlja naslednji korak projekta, ki je svojo pot že začel ter želi svoj doprinos skupnemu dobremu razviti na višji ravni." },

    { h: "Predstavitev zahtevka" },
    { p: "Vsak zahtevek za brezpogojno financiranje je predstavljen podobno kot crowdfunding projekt." },
    { p: "Vsebovati mora:" },
    { ul: [
      "naslov financiranja,",
      "predstavitveno sliko,",
      "ime prosilca,",
      "vrsto financiranja,",
      "kratek povzetek,",
      "osebno zgodbo ali opis projekta,",
      "izbrano FIAT valuto,",
      "želeni FIAT znesek,",
      "namen uporabe sredstev,",
      "pojasnilo, zakaj prosilec potrebuje podporo,",
      "ter njegov pogled na prihodnje vračanje prejete vrednosti.",
    ] },
    { p: "Pri projektu za skupno dobro mora zahtevek vsebovati tudi povezave do predhodnih crowdfunding projektov." },
    { p: "Predstavitev mora biti dovolj osebna, jasna in konkretna, da lahko skupnost razume:" },
    { ul: [
      "komu pomaga,",
      "zakaj človek potrebuje sredstva,",
      "za kaj bodo uporabljena,",
      "ter kaj želi s podporo ustvariti ali spremeniti.",
    ] },

    { h: "Osem dni zorenja" },
    { p: "Ko je zahtevek objavljen, najprej vstopi v obdobje zorenja, ki traja osem dni." },
    { p: "V času zorenja še ni mogoče prispevati sredstev." },
    { p: "Člani skupnosti lahko v tem obdobju:" },
    { ul: [
      "preberejo predstavitev,",
      "postavijo vprašanja,",
      "napišejo komentar,",
      "opozorijo na morebitne nejasnosti,",
      "predlagajo izboljšave,",
      "ter prosilcu pomagajo, da svojo predstavitev dopolni.",
    ] },
    { p: "Prosilec lahko na podlagi komentarjev:" },
    { ul: [
      "odgovori na vprašanja,",
      "pojasni nejasnosti,",
      "dopolni svojo zgodbo,",
      "podrobneje opiše uporabo sredstev,",
      "spremeni ali izboljša besedilo,",
      "ter pripravi čim bolj jasno končno predstavitev.",
    ] },
    { p: "Zorenje ni namenjeno obsojanju človeka ali iskanju razlogov proti financiranju." },
    { p: "Njegov namen je, da se zahtevek skozi komunikacijo razvije, razjasni in dozori, preden začne skupnost vanj namenjati sredstva." },
    { p: "Po osmih dneh zahtevek dozori in financiranje se lahko začne." },

    { h: "Začetek financiranja" },
    { p: "Ko se osemdnevno obdobje zorenja zaključi, lahko člani skupnosti in centralni sklad začnejo prispevati sredstva." },
    { p: "Član ne vpisuje količine LANE, ki jo želi poslati." },
    { p: "Vpiše FIAT znesek, ki ga želi prispevati, na primer:" },
    { ul: ["50 EUR,", "200 EUR,", "1.000 USD,", "ali drug znesek v valuti konkretnega financiranja."] },
    { p: "Sistem nato:" },
    { ol: [
      "prevzame vneseni FIAT znesek,",
      "uporabi trenutno veljavno menjalno razmerje,",
      "izračuna potrebno količino LANE,",
      "samodejno izbere glavno denarnico uporabnika,",
      "prikaže uporabniku celoten obračun,",
      "ter po potrditvi izvede plačilo v LANI.",
    ] },
    { p: "Na enak način se evidentira tudi prispevek centralnega sklada." },

    { h: "Financiranje iz centralnega sklada in skupnosti" },
    { p: "Financiranje je lahko v celoti zagotovljeno iz centralnega sklada, v celoti s strani članov skupnosti ali s kombinacijo obeh virov." },
    { p: "Pri vsakem financiranju je transparentno prikazano:" },
    { ul: [
      "želeni FIAT znesek,",
      "dejansko financirani FIAT znesek,",
      "FIAT vrednost prispevka centralnega sklada,",
      "FIAT vrednost prispevkov članov skupnosti,",
      "število financerjev,",
      "obračunane provizije,",
      "neto vrednost, ki jo je prejel prejemnik financiranja,",
      "že vrnjeni FIAT znesek,",
      "ter preostala odprta FIAT vrednost.",
    ] },
    { p: "Vsak prispevek ima evidentirano tudi količino LANE, s katero je bila transakcija dejansko izvedena, ter uporabljeno menjalno razmerje." },
    { p: "Glavni prikaz in obračun pa sta vedno izražena v izbrani FIAT valuti financiranja." },

    { h: "Provizija ob financiranju" },
    { p: "Ob vsakem posameznem vplačilu v brezpogojno financiranje se prejemniku financiranja obračuna 3-odstotna provizija." },
    { p: "Provizija se obračuna ne glede na to, ali sredstva prispeva:" },
    { ul: ["centralni sklad,", "posamezni član skupnosti,", "ali drug upravičeni financer."] },
    { p: "Če financer prispeva 1.000 EUR, se transakcija evidentira na naslednji način:" },
    { ul: [
      "bruto financirana vrednost: 1.000 EUR,",
      "3-odstotna provizija: 30 EUR,",
      "neto vrednost, ki jo prejme prejemnik financiranja: 970 EUR.",
    ] },
    { p: "Plačilo se dejansko izvede v LANI po menjalnem razmerju, ki velja v trenutku transakcije." },
    { p: "Odprta financirana vrednost se poveča za celotni bruto prispevek v višini 1.000 EUR, saj ta predstavlja vrednost, ki jo je financer namenil financiranju." },
    { p: "Provizija v višini 30 EUR se evidentira ločeno, prejemnik pa prejme LANO v neto vrednosti 970 EUR." },
    { p: "Pred potrditvijo vsakega prispevka morajo biti jasno prikazani:" },
    { ul: [
      "bruto FIAT znesek prispevka,",
      "3-odstotna provizija,",
      "neto FIAT vrednost za prejemnika financiranja,",
      "potrebna količina LANE,",
      "ter uporabljeno menjalno razmerje.",
    ] },

    { h: "Financiranje nima pogoja popolne zbranosti" },
    { p: "Želeni FIAT znesek, ki ga prosilec navede v vlogi, predstavlja njegov cilj, vendar ni pogoj, da mora biti celoten znesek zbran, preden lahko prejme sredstva." },
    { p: "Unconditional Financing ne deluje po načelu »vse ali nič«." },
    { p: "Vsa sredstva, ki jih prosilec prejme od centralnega sklada ali članov skupnosti, se mu sproti izplačujejo v LANI po odbitku 3-odstotne provizije." },
    { p: "To pomeni:" },
    { ul: [
      "da ni treba čakati, da je dosežen celotni cilj,",
      "da se vsak nov FIAT prispevek doda obstoječemu financiranju,",
      "da se pri vsakem prispevku posebej obračuna 3-odstotna provizija,",
      "da sistem izračuna in izplača neto LANA protivrednost,",
      "ter da skupna bruto financirana vrednost raste z vsakim novim prispevkom.",
    ] },
    { p: "Če nekdo zaprosi za financiranje v višini 10.000 EUR in se najprej zbere 2.000 EUR, se evidentira:" },
    { ul: [
      "bruto financirana vrednost: 2.000 EUR,",
      "provizija: 60 EUR,",
      "neto vrednost, ki jo prejme prosilec: 1.940 EUR.",
    ] },
    { p: "Če se pozneje zbere dodatnih 1.500 EUR, se pri tem novem prispevku obračuna:" },
    { ul: [
      "bruto prispevek: 1.500 EUR,",
      "provizija: 45 EUR,",
      "neto izplačilo prejemniku: 1.455 EUR.",
    ] },
    { p: "Končna bruto financirana vrednost je vsota vseh prispevkov, ki so bili vključeni v financiranje." },
    { p: "Neto prejeta vrednost pa predstavlja bruto financirano vrednost, zmanjšano za vse obračunane 3-odstotne provizije ob financiranju." },

    { h: "Kaj se zgodi, če je zbranih sredstev premalo?" },
    { p: "Prosilec sam presodi, ali je neto prejeta vrednost dovolj velika, da lahko z njo uresniči svoj namen." },
    { p: "Če je sredstev manj od želenega zneska, se lahko odloči:" },
    { ul: [
      "da bo namen izvedel v manjšem obsegu,",
      "da bo počakal na dodatne prispevke,",
      "da bo poiskal še druge vire podpore,",
      "ali da bo prejeta sredstva vrnil.",
    ] },
    { p: "Odločitev ostaja pri človeku, ki je zaprosil za financiranje." },
    { p: "Sistem mu ne nalaga, da mora delno zbrani znesek obdržati, če mu ta ne omogoča uresničitve namena." },
    { p: "Če presodi, da je zbranih sredstev premalo, lahko vrne celotni ali del odprte financirane vrednosti." },
    { p: "Ob vračilu sistem izračuna, koliko LANE je v tistem trenutku potrebnih za vračilo izbranega FIAT zneska." },
    { p: "Tudi pri takšnem vračilu se uporabi 3-odstotna provizija, ki se obračuna prejemniku vračila oziroma financerju." },

    { h: "Evidentiranje financerjev" },
    { p: "Za vsak prispevek se zabeležijo:" },
    { ul: [
      "financer,",
      "vrsta financerja,",
      "bruto prispevani FIAT znesek,",
      "valuta financiranja,",
      "3-odstotna provizija prejemnika financiranja,",
      "neto vrednost, ki jo je prejel prejemnik,",
      "količina dejansko prenesene LANE,",
      "uporabljeno menjalno razmerje,",
      "datum prispevka,",
      "vračilna denarnica,",
      "ter delež financerja v celotni bruto financirani FIAT vrednosti.",
    ] },
    { p: "Delež posameznega financerja se izračuna glede na bruto FIAT vrednost njegovega prispevka." },
    { p: "Če je bilo financiranje zagotovljeno tako:" },
    { ul: [
      "centralni sklad: 4.000 EUR,",
      "prvi član: 3.000 EUR,",
      "drugi član: 2.000 EUR,",
      "tretji član: 1.000 EUR,",
    ] },
    { p: "znaša skupna bruto financirana vrednost 10.000 EUR." },
    { p: "Deleži financerjev so zato:" },
    { ul: [
      "centralni sklad: 40 odstotkov,",
      "prvi član: 30 odstotkov,",
      "drugi član: 20 odstotkov,",
      "tretji član: 10 odstotkov.",
    ] },
    { p: "Količina LANE, ki jo je posamezni financer nakazal, ne določa njegovega deleža." },
    { p: "Pomembna je FIAT vrednost njegovega prispevka v trenutku izvedbe transakcije." },

    { h: "Vračilne denarnice" },
    { p: "Ko član skupnosti prispeva sredstva, sistem samodejno določi njegovo glavno denarnico kot denarnico za prihodnja vračila." },
    { p: "Na to denarnico bo prejemal svoj sorazmerni delež vseh vračil, zmanjšan za 3-odstotno provizijo ob vračilu." },
    { p: "Pri centralnem skladu se vračila usmerjajo nazaj v namensko denarnico centralnega sklada Unconditional Financing." },
    { p: "Pred potrditvijo prispevka lahko uporabnik vidi:" },
    { ul: [
      "bruto FIAT vrednost svojega prispevka,",
      "trenutno potrebno količino LANE,",
      "uporabljeno menjalno razmerje,",
      "svoj pričakovani delež financiranja,",
      "ter denarnico, na katero bo prejemal prihodnja vračila.",
    ] },

    { h: "Spreminjanje vrednosti LANE" },
    { p: "Ker se vse financirane vrednosti vodijo v FIAT valuti, sprememba vrednosti LANE ne spremeni FIAT višine odprtega financiranja." },
    { p: "Če je nekdo prejel financiranje z bruto vrednostjo 10.000 EUR, njegova odprta vrednost ostaja izražena v evrih." },
    { p: "Količina LANE, potrebna za posamezno financiranje ali vračilo, pa je odvisna od menjalnega razmerja v trenutku izvedbe transakcije." },
    { p: "To pomeni:" },
    { ul: [
      "pri financiranju se FIAT znesek pretvori v LANO po takratnem menjalnem razmerju,",
      "pri vračilu se FIAT znesek ponovno pretvori v LANO po razmerju, ki velja v trenutku vračila,",
      "odprta financirana vrednost pa ves čas ostaja izražena v izbrani FIAT valuti.",
    ] },
    { p: "LANA je tako sredstvo prenosa vrednosti, FIAT valuta pa osnovna obračunska enota financiranja." },

    { h: "Vračanje prejete vrednosti" },
    { p: "Prejemnik lahko prejeto financirano vrednost vrača kadarkoli in v poljubnih FIAT zneskih." },
    { p: "Pri vračilu:" },
    { ol: [
      "izbere financiranje,",
      "vnese bruto FIAT znesek, ki ga želi vrniti,",
      "sistem izračuna trenutno potrebno količino LANE,",
      "prikaže uporabljeno menjalno razmerje,",
      "prikaže razdelitev vračila med financerje,",
      "prikaže 3-odstotno provizijo posameznega prejemnika vračila,",
      "ter po potrditvi izvede plačilo v LANI.",
    ] },
    { p: "Odprta financirana vrednost se zmanjša za celotni bruto FIAT znesek vračila." },
    { p: "Če prejemnik vrne 1.000 EUR, se njegovo odprto stanje zmanjša za 1.000 EUR." },
    { p: "Financerji pa skupaj prejmejo neto vrednost 970 EUR, saj se jim ob vračilu obračuna 3-odstotna provizija v skupni višini 30 EUR." },

    { h: "Sorazmerna razdelitev vračil" },
    { p: "Sistem bruto FIAT vrednost vračila avtomatsko razdeli med centralni sklad in vse člane, ki so sodelovali pri financiranju." },
    { p: "Razdelitev se izvede glede na njihov delež v celotni bruto financirani FIAT vrednosti." },
    { p: "Če je bilo financiranje zagotovljeno tako:" },
    { ul: [
      "centralni sklad: 40 odstotkov,",
      "prvi član: 30 odstotkov,",
      "drugi član: 20 odstotkov,",
      "tretji član: 10 odstotkov,",
    ] },
    { p: "se bruto vračilo v višini 1.000 EUR najprej razdeli tako:" },
    { ul: [
      "centralni sklad: 400 EUR,",
      "prvi član: 300 EUR,",
      "drugi član: 200 EUR,",
      "tretji član: 100 EUR.",
    ] },
    { p: "Nato se vsakemu prejemniku obračuna 3-odstotna provizija." },
    { p: "Neto razdelitev je zato:" },
    { ul: [
      "centralni sklad prejme LANO v vrednosti 388 EUR, provizija znaša 12 EUR,",
      "prvi član prejme LANO v vrednosti 291 EUR, provizija znaša 9 EUR,",
      "drugi član prejme LANO v vrednosti 194 EUR, provizija znaša 6 EUR,",
      "tretji član prejme LANO v vrednosti 97 EUR, provizija znaša 3 EUR.",
    ] },
    { p: "Skupno bruto vračilo znaša 1.000 EUR." },
    { p: "Skupna provizija znaša 30 EUR." },
    { p: "Financerji skupaj prejmejo LANO v neto vrednosti 970 EUR." },
    { p: "Prejemniku financiranja ni treba izvajati posameznih transakcij za vsakega financerja. Sistem celotno razdelitev in obračun provizij izvede avtomatsko." },

    { h: "Provizija ob vračilu financiranja" },
    { p: "Ob vsakem posameznem vračilu se financerju oziroma prejemniku vračila obračuna 3-odstotna provizija." },
    { p: "To velja za:" },
    { ul: ["posamezne člane skupnosti,", "centralni sklad,", "ter vse druge financerje."] },
    { p: "Provizija se obračuna od bruto FIAT vrednosti, ki pri posameznem vračilu pripada financerju." },
    { p: "Če financerju pri vračilu pripada 100 EUR, se transakcija evidentira tako:" },
    { ul: [
      "bruto delež vračila: 100 EUR,",
      "3-odstotna provizija: 3 EUR,",
      "neto vrednost, ki jo prejme financer: 97 EUR.",
    ] },
    { p: "Financer prejme LANO v vrednosti 97 EUR po menjalnem razmerju, ki velja v trenutku vračila." },
    { p: "V njegovi evidenci so ločeno prikazani:" },
    { ul: [
      "bruto vrednost vračila,",
      "obračunana provizija,",
      "neto prejeta vrednost,",
      "količina prejete LANE,",
      "ter uporabljeno menjalno razmerje.",
    ] },

    { h: "Skupna struktura provizij" },
    { p: "Pri vsakem brezpogojnem financiranju obstajata dve ločeni 3-odstotni proviziji." },
    { h: "1. Provizija prejemnika financiranja" },
    { p: "Ob vsakem novem prispevku se prejemniku financiranja obračunajo 3 odstotki od bruto financirane vrednosti." },
    { p: "Prejemnik zato prejme 97 odstotkov bruto financirane FIAT vrednosti." },
    { p: "Celotni bruto prispevek pa se zabeleži kot del odprte financirane vrednosti." },
    { h: "2. Provizija financerja" },
    { p: "Ob vsakem vračilu se vsakemu financerju obračunajo 3 odstotki od njegovega bruto deleža vračila." },
    { p: "Financer zato prejme 97 odstotkov FIAT vrednosti, ki mu pri posameznem vračilu pripada." },
    { p: "Odprta financirana vrednost se kljub temu zmanjša za celotni bruto znesek, ki ga je prejemnik vrnil." },
    { p: "Proviziji nista obresti." },
    { p: "Nista odvisni od časa trajanja financiranja in se ne povečujeta, če se financiranje vrača daljše obdobje." },
    { p: "Obračunata se samo ob dejansko izvedeni transakciji:" },
    { ul: ["prvič ob financiranju,", "drugič ob vračilu."] },

    { h: "Primer celotnega toka financiranja" },
    { p: "Financer prispeva bruto vrednost v višini 1.000 EUR." },
    { p: "Ob financiranju se prejemniku obračuna 3-odstotna provizija:" },
    { ul: [
      "bruto financirana vrednost: 1.000 EUR,",
      "provizija prejemnika financiranja: 30 EUR,",
      "neto vrednost, ki jo prejme prejemnik: 970 EUR.",
    ] },
    { p: "Odprta financirana vrednost znaša 1.000 EUR." },
    { p: "Prejemnik pozneje vrne celotnih 1.000 EUR." },
    { p: "Ob vračilu se financerju obračuna dodatna 3-odstotna provizija:" },
    { ul: [
      "bruto vračilo: 1.000 EUR,",
      "provizija financerja: 30 EUR,",
      "neto vrednost, ki jo prejme financer: 970 EUR.",
    ] },
    { p: "Po izvedbi vračila je financiranje v celoti zaključeno." },
    { p: "Celotna provizija sistema pri tem financiranju znaša:" },
    { ul: ["30 EUR ob financiranju,", "30 EUR ob vračilu,", "skupaj 60 EUR."] },
    { p: "Vse transakcije so dejansko izvedene v LANI, vsi obračuni pa so prikazani v izbrani FIAT valuti financiranja." },

    { h: "Sprememba menjalnega razmerja med financiranjem in vračilom" },
    { p: "Financer ob vračilu ne prejme nujno enakega števila LANA, kot jih je prvotno prispeval." },
    { p: "Prejme LANO v neto FIAT vrednosti, ki mu pripada po odbitku 3-odstotne provizije." },
    { p: "Če financerju pri posameznem vračilu pripada bruto vrednost 200 EUR, se mu obračuna 6 EUR provizije." },
    { p: "Prejme LANO v trenutni vrednosti 194 EUR." },
    { p: "Sistem ob vračilu izračuna, koliko LANE je v tistem trenutku vrednih 194 EUR, in to količino nakaže na njegovo vračilno denarnico." },
    { p: "Tako vrednost financiranja ostaja stabilna in razumljiva tudi takrat, ko se menjalno razmerje LANE skozi čas spreminja." },

    { h: "Moje brezpogojne podpore" },
    { p: "Vsak uporabnik ima pregled vseh financiranj, ki jih je podprl." },
    { p: "Pri vsaki podpori vidi:" },
    { ul: [
      "komu je namenil sredstva,",
      "bruto FIAT vrednost svojega prispevka,",
      "valuto financiranja,",
      "količino dejansko poslane LANE,",
      "uporabljeno menjalno razmerje,",
      "svoj delež v celotnem financiranju,",
      "bruto vrednost dosedanjih vračil,",
      "obračunane 3-odstotne provizije,",
      "neto vrednost, ki jo je že prejel,",
      "koliko bruto FIAT vrednosti mu mora biti še vrnjene,",
      "ter trenutni status financiranja.",
    ] },
    { p: "Glavni prikaz je vedno v FIAT valuti posameznega financiranja." },

    { h: "Moja brezpogojna financiranja" },
    { p: "Uporabnik vidi tudi vsa brezpogojna financiranja, ki jih je sam ustvaril ali prejel." },
    { p: "Pri vsakem financiranju vidi:" },
    { ul: [
      "želeni FIAT znesek,",
      "izbrano valuto,",
      "bruto financirani FIAT znesek,",
      "provizije, obračunane ob financiranju,",
      "neto FIAT vrednost, ki jo je dejansko prejel,",
      "prispevek centralnega sklada,",
      "prispevke članov skupnosti,",
      "število financerjev,",
      "že vrnjeni bruto FIAT znesek,",
      "preostalo odprto FIAT vrednost,",
      "zgodovino vseh prispevkov, provizij in vračil,",
      "ter možnost novega vračila.",
    ] },
    { p: "Če presodi, da delno zbrana sredstva ne zadostujejo za njegov namen, lahko vrne celotno ali del odprte financirane vrednosti." },

    { h: "Brezpogojnost in samoodgovornost" },
    { p: "Brezpogojno financiranje se prejme z iskrenim namenom, da bo človek prejeto vrednost vrnil, ko mu bo to omogočala njegova življenjska situacija." },
    { p: "Vračanje ni vezano na:" },
    { ul: [
      "fiksne mesečne obroke,",
      "obresti,",
      "kazni,",
      "zavarovanje,",
      "ali klasično preverjanje kreditne sposobnosti.",
    ] },
    { p: "Človek lahko sredstva vrača postopoma in glede na svoje resnične zmožnosti." },
    { p: "Če se zgodijo resne življenjske okoliščine, zaradi katerih prejete vrednosti objektivno ni mogoče vrniti, človek zaradi tega ne postane klasični dolžnik, ki bi ga skupnost kaznovala ali preganjala." },
    { p: "Če prejete vrednosti resnično ne more vrniti, mu je ni treba vrniti." },
    { p: "Brezpogojnost pa ne pomeni, da človek prejme financiranje brez namena vračila." },
    { p: "Vsak član k financiranju pristopi samoodgovorno in z iskrenim namenom, da bo prejeto vrednost skozi svoje življenje, delo, projekte ali sredstva, ki jih prejema v Lana8Wonder, postopoma vrnil v skupni tok." },
    { p: "Pomeni, da zaupanje, transparentnost in samoodgovornost nadomestijo prisilo, obresti in strah." },
    { p: "Človek ostaja pomembnejši od odprte finančne obveznosti." },

    { h: "Kroženje podpore" },
    { p: "Ko centralni sklad ali član skupnosti prispeva k brezpogojnemu financiranju, se vrednost dejansko prenese v LANI." },
    { p: "Najprej pomaga človeku, ki jo potrebuje." },
    { p: "Ko ta začne prejeto vrednost vračati, se LANA v ustrezni neto FIAT vrednosti:" },
    { ul: [
      "vrne članom, ki so mu zaupali,",
      "vrne v centralni sklad,",
      "ter lahko ponovno postane podpora naslednjemu človeku ali projektu.",
    ] },
    { p: "Provizije, obračunane ob financiranju in vračanju, omogočajo razvoj, vzdrževanje in dolgoročno delovanje sistema Unconditional Financing." },
    { p: "Tako ista LANA skozi čas pomaga več ljudem." },
    { p: "Nekdo danes prejme podporo skupnosti. Jutri lahko s svojim vračilom, delovanjem in prispevkom omogoči podporo nekomu drugemu." },
    { p: "Unconditional Financing zato ni samo sistem prenosa denarja." },
    { p: "Je skupnostni sistem, v katerem zaupanje, podpora, samoodgovornost in obilje dejansko krožijo med ljudmi." },

    { h: "Nadaljnji razvoj" },
    { p: "Natančen opis posameznih strani, uporabniških vmesnikov, obrazcev, statusov, provizijskih računov in tehničnega zapisovanja bo pripravljen ločeno v okviru produktne in tehnične specifikacije modula Unconditional Financing." },
  ],
};

// ── English (translation) ──
const EN: Article = {
  title: "Unconditional Financing in the Lana Ecosystem",
  subtitle: "A community that trusts the person",
  blocks: [
    { p: "Unconditional financing is a new form of community financing within the Lana ecosystem." },
    { p: "It allows community members to receive support in moments of personal hardship, in transitioning to a more natural way of living, or in creating projects, products, and services for the common good." },
    { p: "The financing can be provided by:" },
    { ul: [
      "the central Unconditional Financing fund,",
      "individual members of the Lana community,",
      "or the central fund and community members together.",
    ] },
    { p: "Unconditional financing is not based on classic banking assessment, assets, employment, collateral, interest, or proof of creditworthiness." },
    { p: "Its foundations are:" },
    { ul: [
      "trust,",
      "transparency,",
      "active involvement in the community,",
      "self-responsibility,",
      "mutual support,",
      "and a readiness to return the received value into the shared flow whenever that is possible.",
    ] },

    { h: "Unconditional does not mean without self-responsibility." },
    { p: "It means we do not make a person conditional on their past, their financial situation, or their assets. We look at their true presence, their relationship with the community, the purpose of the financing, and the direction in which they want to step with the community's support." },

    { h: "The financing is denominated in FIAT currency" },
    { p: "Every unconditional financing is denominated and tracked in a chosen FIAT currency." },
    { p: "When submitting a request, the applicant:" },
    { ul: [
      "enters the desired amount,",
      "chooses the FIAT currency of the financing,",
      "and presents the purpose and expected scope of the financing in that currency.",
    ] },
    { p: "These can be, for example:" },
    { ul: ["EUR,", "USD,", "GBP,", "or other currencies supported by the Lana ecosystem."] },
    { p: "If the financing is created in euros, the following are tracked in euros:" },
    { ul: [
      "the desired amount,",
      "the value of individual contributions,",
      "the total financed value,",
      "the amount already returned,",
      "the remaining open value,",
      "the fees charged,",
      "and the net value received and paid out.",
    ] },
    { p: "All actual payments are executed in LANA." },
    { p: "With every contribution or repayment, the system automatically calculates how much LANA the chosen FIAT amount represents, based on the exchange rate valid at the moment of the transaction." },
    { p: "Users therefore always think and communicate in FIAT amounts, while LANA is the means by which the value is actually transferred." },

    { h: "Who can request unconditional financing?" },
    { p: "A request for new unconditional financing can be submitted by a user who has been a Lana8Wonder member for at least four completed Splits." },
    { p: "This condition ensures that, before asking for financing, a person first becomes part of the Lana ecosystem, gets to know how it works, and develops a relationship with the community." },
    { p: "Unconditional financing is not intended for people who join the system only in order to immediately request funds." },
    { p: "It is intended for active members who are part of the community and who, with the support of others, wish to:" },
    { ul: [
      "get through personal hardship,",
      "make an important shift in life,",
      "or create something that will serve the common good.",
    ] },

    { h: "Three types of unconditional financing" },
    { p: "When submitting a request, every applicant chooses one of three types of financing." },

    { h: "1. Financing to address personal hardship" },
    { p: "This form of financing is intended for a person who finds themselves in a personal, life, or financial situation in which they need the community's help." },
    { p: "They may need the funds, for example, for:" },
    { ul: [
      "settling urgent obligations,",
      "sorting out their living situation,",
      "treatment or recovery,",
      "moving,",
      "education,",
      "helping their family,",
      "re-establishing personal stability,",
      "or another sincere life need.",
    ] },
    { p: "A person does not have to prove that the received funds will generate a profit." },
    { p: "The purpose of the financing is for the community to help them restore balance, breathe, and take the next step." },

    { h: "2. Financing a transition to a more natural way of life" },
    { p: "This form of financing is intended for people who want to make a concrete shift toward a more natural, healthy, high-quality, and self-sufficient way of living." },
    { p: "The funds can be used, for example, for:" },
    { ul: [
      "moving to a more natural environment,",
      "setting up a home or land,",
      "growing their own food,",
      "buying equipment for greater self-sufficiency,",
      "creating a healthier living environment,",
      "reducing dependence on the existing system,",
      "or another change that brings a person closer to nature and to a higher quality of life.",
    ] },
    { p: "In this way the community supports not only the individual, but also the broader transition to a more natural, high-quality, and balanced way of living." },

    { h: "3. Financing a project intended for the common good" },
    { p: "This form of financing is intended for developing a project, product, service, or organization that creates something good for people, the community, animals, nature, and life as a whole." },
    { p: "This is not classic business financing whose main purpose is increasing profit, expanding a company, or creating new conventional jobs." },
    { p: "It is support for projects that arise in the spirit of the Economy of Abundance." },
    { p: "Such projects can generate income and can be commercially successful, but money is not their ultimate purpose." },
    { p: "Money is the means that allows them to create higher-quality products and services, develop the community, and contribute to the common good." },
    { p: "Supported projects must contribute to:" },
    { ul: [
      "a higher quality of life,",
      "the health and well-being of people,",
      "the growth of the Lana community,",
      "the creation of higher-quality products and services,",
      "connection and cooperation between people,",
      "respect for the person and their dignity,",
      "the protection of nature, animals, and the planet,",
      "preserving and nurturing all that is alive,",
      "the development of a more natural and responsible economy,",
      "or inspiring others to also start creating for the common good.",
    ] },
    { p: "The fundamental purpose of such a project is not merely to sell a product or a service." },
    { p: "Its purpose is to create something that improves life, raises quality, protects natural balance, and contributes to a more beautiful and more humane world." },

    { h: "The Economy of Abundance" },
    { p: "The Economy of Abundance represents a transition from an economy of scarcity, competition, and creating primarily for profit, to an economy that places life at its centre." },
    { p: "In the Economy of Abundance we do not create as many products and services as possible just to increase consumption." },
    { p: "We create better, with higher quality, and at a higher level." },
    { p: "We create products and services that:" },
    { ul: [
      "have real value for the person,",
      "improve the quality of life,",
      "are created with care, knowledge, and love,",
      "respect the people who create and use them,",
      "do not destroy nature for short-term profit,",
      "do not exploit animals or other living beings,",
      "are high-quality, durable, and responsibly made,",
      "and leave more life behind them, not less.",
    ] },
    { p: "The Economy of Abundance means that, as a community, we allow ourselves to create the best we are capable of." },
    { p: "We do not look for the cheapest solution regardless of the consequences, but for the solution that is good for the person, the community, nature, and future generations." },
    { p: "In such an economy, a project's success is not determined only by sales volume or the size of the profit." },
    { p: "Success also means:" },
    { ul: [
      "how much good the project has created,",
      "how many people it has supported or inspired,",
      "how it has improved the quality of life,",
      "how responsibly it has treated nature and resources,",
      "and whether, through its existence, it has contributed to preserving all that is alive.",
    ] },
    { p: "Unconditional financing of projects for the common good is therefore intended for people who do not want to create only for themselves." },
    { p: "It is intended for those who, through their work, products, and services, wish to create abundance that spreads among people while respecting life in all its forms." },

    { h: "Mandatory prior crowdfunding" },
    { p: "For financing a project intended for the common good, at least one crowdfunding project connected to the same idea or its development must have been carried out before the request is submitted." },
    { p: "In the application, the applicant must clearly state:" },
    { ul: [
      "which crowdfunding project or projects the financing relates to,",
      "what has already been created through the crowdfunding,",
      "how much support the project has already received,",
      "which stage of development the project is in,",
      "how the project contributes to the Economy of Abundance,",
      "how its products or services serve the common good,",
      "how the project respects and preserves all that is alive,",
      "and why it needs unconditional financing for the next step.",
    ] },
    { p: "Crowdfunding is the first step, through which an idea is presented to the community, receives initial support, and begins to develop." },
    { p: "Unconditional financing is the next step of a project that has already begun its path and wants to develop its contribution to the common good at a higher level." },

    { h: "Presenting the request" },
    { p: "Every request for unconditional financing is presented much like a crowdfunding project." },
    { p: "It must contain:" },
    { ul: [
      "the title of the financing,",
      "a presentation image,",
      "the applicant's name,",
      "the type of financing,",
      "a short summary,",
      "a personal story or a description of the project,",
      "the chosen FIAT currency,",
      "the desired FIAT amount,",
      "the intended use of the funds,",
      "an explanation of why the applicant needs support,",
      "and their view on returning the received value in the future.",
    ] },
    { p: "For a project for the common good, the request must also contain links to the prior crowdfunding projects." },
    { p: "The presentation must be personal, clear, and concrete enough for the community to understand:" },
    { ul: [
      "who it helps,",
      "why the person needs the funds,",
      "what they will be used for,",
      "and what they wish to create or change with the support.",
    ] },

    { h: "Eight days of maturing" },
    { p: "Once the request is published, it first enters a maturing period that lasts eight days." },
    { p: "During the maturing period it is not yet possible to contribute funds." },
    { p: "In this period, community members can:" },
    { ul: [
      "read the presentation,",
      "ask questions,",
      "write a comment,",
      "point out any ambiguities,",
      "suggest improvements,",
      "and help the applicant complete their presentation.",
    ] },
    { p: "Based on the comments, the applicant can:" },
    { ul: [
      "answer questions,",
      "clarify ambiguities,",
      "expand their story,",
      "describe the use of the funds in more detail,",
      "change or improve the text,",
      "and prepare the clearest possible final presentation.",
    ] },
    { p: "Maturing is not meant for judging a person or looking for reasons against the financing." },
    { p: "Its purpose is for the request to develop, become clear, and mature through communication, before the community starts directing funds into it." },
    { p: "After eight days the request matures and financing can begin." },

    { h: "The start of financing" },
    { p: "Once the eight-day maturing period ends, community members and the central fund can begin contributing funds." },
    { p: "A member does not enter the amount of LANA they wish to send." },
    { p: "They enter the FIAT amount they wish to contribute, for example:" },
    { ul: ["50 EUR,", "200 EUR,", "1,000 USD,", "or another amount in the currency of that particular financing."] },
    { p: "The system then:" },
    { ol: [
      "takes the entered FIAT amount,",
      "applies the currently valid exchange rate,",
      "calculates the required amount of LANA,",
      "automatically selects the user's main wallet,",
      "shows the user the full breakdown,",
      "and, after confirmation, executes the payment in LANA.",
    ] },
    { p: "A contribution from the central fund is recorded in the same way." },

    { h: "Financing from the central fund and the community" },
    { p: "A financing can be fully provided by the central fund, fully by community members, or by a combination of both sources." },
    { p: "For every financing, the following is shown transparently:" },
    { ul: [
      "the desired FIAT amount,",
      "the actually financed FIAT amount,",
      "the FIAT value of the central fund's contribution,",
      "the FIAT value of community members' contributions,",
      "the number of financiers,",
      "the fees charged,",
      "the net value received by the recipient of the financing,",
      "the FIAT amount already returned,",
      "and the remaining open FIAT value.",
    ] },
    { p: "Each contribution also records the amount of LANA with which the transaction was actually executed, along with the exchange rate used." },
    { p: "The main display and accounting, however, are always expressed in the chosen FIAT currency of the financing." },

    { h: "Fee upon financing" },
    { p: "For every individual payment into an unconditional financing, a 3 percent fee is charged to the recipient of the financing." },
    { p: "The fee is charged regardless of whether the funds are contributed by:" },
    { ul: ["the central fund,", "an individual community member,", "or another eligible financier."] },
    { p: "If a financier contributes 1,000 EUR, the transaction is recorded as follows:" },
    { ul: [
      "gross financed value: 1,000 EUR,",
      "3 percent fee: 30 EUR,",
      "net value received by the recipient of the financing: 970 EUR.",
    ] },
    { p: "The payment is actually executed in LANA at the exchange rate valid at the moment of the transaction." },
    { p: "The open financed value increases by the entire gross contribution of 1,000 EUR, since this represents the value the financier directed into the financing." },
    { p: "The fee of 30 EUR is recorded separately, while the recipient receives LANA with a net value of 970 EUR." },
    { p: "Before every contribution is confirmed, the following must be clearly shown:" },
    { ul: [
      "the gross FIAT amount of the contribution,",
      "the 3 percent fee,",
      "the net FIAT value for the recipient of the financing,",
      "the required amount of LANA,",
      "and the exchange rate used.",
    ] },

    { h: "Financing has no all-or-nothing condition" },
    { p: "The desired FIAT amount stated in the application is the applicant's goal, but it is not a condition that the entire amount must be collected before they can receive funds." },
    { p: "Unconditional Financing does not work on an “all or nothing” principle." },
    { p: "All funds the applicant receives from the central fund or from community members are paid out to them in LANA as they come in, after the 3 percent fee is deducted." },
    { p: "This means:" },
    { ul: [
      "that there is no need to wait for the full goal to be reached,",
      "that every new FIAT contribution is added to the existing financing,",
      "that a 3 percent fee is charged separately on each contribution,",
      "that the system calculates and pays out the net LANA equivalent,",
      "and that the total gross financed value grows with every new contribution.",
    ] },
    { p: "If someone requests financing of 10,000 EUR and 2,000 EUR is collected first, the following is recorded:" },
    { ul: [
      "gross financed value: 2,000 EUR,",
      "fee: 60 EUR,",
      "net value received by the applicant: 1,940 EUR.",
    ] },
    { p: "If an additional 1,500 EUR is collected later, the following is charged on that new contribution:" },
    { ul: [
      "gross contribution: 1,500 EUR,",
      "fee: 45 EUR,",
      "net payout to the recipient: 1,455 EUR.",
    ] },
    { p: "The final gross financed value is the sum of all contributions included in the financing." },
    { p: "The net value received is the gross financed value reduced by all the 3 percent fees charged upon financing." },

    { h: "What happens if too little is collected?" },
    { p: "The applicant themselves judges whether the net value received is large enough to realize their purpose." },
    { p: "If there is less than the desired amount, they can decide:" },
    { ul: [
      "to carry out the purpose on a smaller scale,",
      "to wait for additional contributions,",
      "to look for other sources of support,",
      "or to return the received funds.",
    ] },
    { p: "The decision remains with the person who requested the financing." },
    { p: "The system does not require them to keep a partially collected amount if it does not allow them to realize their purpose." },
    { p: "If they judge that too little has been collected, they can return all or part of the open financed value." },
    { p: "Upon repayment, the system calculates how much LANA is needed at that moment to return the chosen FIAT amount." },
    { p: "For such a repayment too, a 3 percent fee applies, charged to the recipient of the repayment, that is, to the financier." },

    { h: "Recording the financiers" },
    { p: "For every contribution, the following are recorded:" },
    { ul: [
      "the financier,",
      "the type of financier,",
      "the gross contributed FIAT amount,",
      "the currency of the financing,",
      "the 3 percent fee of the recipient of the financing,",
      "the net value received by the recipient,",
      "the amount of LANA actually transferred,",
      "the exchange rate used,",
      "the date of the contribution,",
      "the repayment wallet,",
      "and the financier's share in the total gross financed FIAT value.",
    ] },
    { p: "Each financier's share is calculated according to the gross FIAT value of their contribution." },
    { p: "If, for example, the financing was provided as follows:" },
    { ul: [
      "central fund: 4,000 EUR,",
      "first member: 3,000 EUR,",
      "second member: 2,000 EUR,",
      "third member: 1,000 EUR,",
    ] },
    { p: "the total gross financed value amounts to 10,000 EUR." },
    { p: "The financiers' shares are therefore:" },
    { ul: [
      "central fund: 40 percent,",
      "first member: 30 percent,",
      "second member: 20 percent,",
      "third member: 10 percent.",
    ] },
    { p: "The amount of LANA an individual financier transferred does not determine their share." },
    { p: "What matters is the FIAT value of their contribution at the moment the transaction was executed." },

    { h: "Repayment wallets" },
    { p: "When a community member contributes funds, the system automatically sets their main wallet as the wallet for future repayments." },
    { p: "They will receive their proportional share of all repayments into that wallet, reduced by the 3 percent fee charged upon repayment." },
    { p: "For the central fund, repayments are directed back into the dedicated wallet of the central Unconditional Financing fund." },
    { p: "Before confirming a contribution, the user can see:" },
    { ul: [
      "the gross FIAT value of their contribution,",
      "the amount of LANA currently required,",
      "the exchange rate used,",
      "their expected share of the financing,",
      "and the wallet into which they will receive future repayments.",
    ] },

    { h: "Changes in the value of LANA" },
    { p: "Because all financed values are tracked in FIAT currency, a change in the value of LANA does not change the FIAT size of the open financing." },
    { p: "If someone received financing with a gross value of 10,000 EUR, their open value remains expressed in euros." },
    { p: "The amount of LANA required for a particular financing or repayment, however, depends on the exchange rate at the moment the transaction is executed." },
    { p: "This means:" },
    { ul: [
      "upon financing, the FIAT amount is converted into LANA at the exchange rate at that time,",
      "upon repayment, the FIAT amount is converted into LANA again at the rate valid at the moment of repayment,",
      "while the open financed value remains expressed in the chosen FIAT currency at all times.",
    ] },
    { p: "LANA is thus the means of transferring value, while the FIAT currency is the basic unit of account of the financing." },

    { h: "Returning the received value" },
    { p: "The recipient can return the received financed value at any time and in any FIAT amounts." },
    { p: "Upon repayment, they:" },
    { ol: [
      "select the financing,",
      "enter the gross FIAT amount they wish to return,",
      "the system calculates the amount of LANA currently required,",
      "it shows the exchange rate used,",
      "it shows how the repayment is distributed among the financiers,",
      "it shows the 3 percent fee of each recipient of the repayment,",
      "and, after confirmation, executes the payment in LANA.",
    ] },
    { p: "The open financed value is reduced by the entire gross FIAT amount of the repayment." },
    { p: "If the recipient returns 1,000 EUR, their open balance is reduced by 1,000 EUR." },
    { p: "The financiers together, however, receive a net value of 970 EUR, since a 3 percent fee totalling 30 EUR is charged to them upon repayment." },

    { h: "Proportional distribution of repayments" },
    { p: "The system automatically distributes the gross FIAT value of the repayment between the central fund and all members who took part in the financing." },
    { p: "The distribution is carried out according to their share in the total gross financed FIAT value." },
    { p: "If the financing was provided as follows:" },
    { ul: [
      "central fund: 40 percent,",
      "first member: 30 percent,",
      "second member: 20 percent,",
      "third member: 10 percent,",
    ] },
    { p: "a gross repayment of 1,000 EUR is first distributed as follows:" },
    { ul: [
      "central fund: 400 EUR,",
      "first member: 300 EUR,",
      "second member: 200 EUR,",
      "third member: 100 EUR.",
    ] },
    { p: "Then a 3 percent fee is charged to each recipient." },
    { p: "The net distribution is therefore:" },
    { ul: [
      "the central fund receives LANA worth 388 EUR, the fee amounts to 12 EUR,",
      "the first member receives LANA worth 291 EUR, the fee amounts to 9 EUR,",
      "the second member receives LANA worth 194 EUR, the fee amounts to 6 EUR,",
      "the third member receives LANA worth 97 EUR, the fee amounts to 3 EUR.",
    ] },
    { p: "The total gross repayment amounts to 1,000 EUR." },
    { p: "The total fee amounts to 30 EUR." },
    { p: "The financiers together receive LANA with a net value of 970 EUR." },
    { p: "The recipient of the financing does not have to carry out individual transactions for each financier. The system performs the entire distribution and fee accounting automatically." },

    { h: "Fee upon repayment of the financing" },
    { p: "For every individual repayment, a 3 percent fee is charged to the financier, that is, to the recipient of the repayment." },
    { p: "This applies to:" },
    { ul: ["individual community members,", "the central fund,", "and all other financiers."] },
    { p: "The fee is charged on the gross FIAT value that belongs to the financier in that particular repayment." },
    { p: "If 100 EUR belongs to a financier in a repayment, the transaction is recorded as follows:" },
    { ul: [
      "gross share of the repayment: 100 EUR,",
      "3 percent fee: 3 EUR,",
      "net value received by the financier: 97 EUR.",
    ] },
    { p: "The financier receives LANA worth 97 EUR at the exchange rate valid at the moment of the repayment." },
    { p: "Their record shows separately:" },
    { ul: [
      "the gross value of the repayment,",
      "the fee charged,",
      "the net value received,",
      "the amount of LANA received,",
      "and the exchange rate used.",
    ] },

    { h: "The overall fee structure" },
    { p: "In every unconditional financing there are two separate 3 percent fees." },
    { h: "1. The fee of the recipient of the financing" },
    { p: "With every new contribution, 3 percent of the gross financed value is charged to the recipient of the financing." },
    { p: "The recipient therefore receives 97 percent of the gross financed FIAT value." },
    { p: "The entire gross contribution, however, is recorded as part of the open financed value." },
    { h: "2. The fee of the financier" },
    { p: "With every repayment, 3 percent of their gross share of the repayment is charged to each financier." },
    { p: "The financier therefore receives 97 percent of the FIAT value that belongs to them in that particular repayment." },
    { p: "The open financed value is nevertheless reduced by the entire gross amount the recipient returned." },
    { p: "The fees are not interest." },
    { p: "They do not depend on how long the financing lasts and do not increase if the financing is repaid over a longer period." },
    { p: "They are charged only on an actually executed transaction:" },
    { ul: ["the first time upon financing,", "the second time upon repayment."] },

    { h: "An example of the full financing flow" },
    { p: "A financier contributes a gross value of 1,000 EUR." },
    { p: "Upon financing, a 3 percent fee is charged to the recipient:" },
    { ul: [
      "gross financed value: 1,000 EUR,",
      "fee of the recipient of the financing: 30 EUR,",
      "net value received by the recipient: 970 EUR.",
    ] },
    { p: "The open financed value amounts to 1,000 EUR." },
    { p: "The recipient later returns the full 1,000 EUR." },
    { p: "Upon repayment, an additional 3 percent fee is charged to the financier:" },
    { ul: [
      "gross repayment: 1,000 EUR,",
      "fee of the financier: 30 EUR,",
      "net value received by the financier: 970 EUR.",
    ] },
    { p: "Once the repayment is carried out, the financing is fully concluded." },
    { p: "The system's total fee for this financing amounts to:" },
    { ul: ["30 EUR upon financing,", "30 EUR upon repayment,", "60 EUR in total."] },
    { p: "All transactions are actually executed in LANA, while all accounting is displayed in the chosen FIAT currency of the financing." },

    { h: "A change in the exchange rate between financing and repayment" },
    { p: "Upon repayment, a financier does not necessarily receive the same number of LANA they originally contributed." },
    { p: "They receive LANA with the net FIAT value that belongs to them after the 3 percent fee is deducted." },
    { p: "If a gross value of 200 EUR belongs to a financier in a particular repayment, a fee of 6 EUR is charged to them." },
    { p: "They receive LANA with a current value of 194 EUR." },
    { p: "Upon repayment, the system calculates how much LANA is worth 194 EUR at that moment and transfers that amount to their repayment wallet." },
    { p: "In this way the value of the financing remains stable and understandable even when the exchange rate of LANA changes over time." },

    { h: "My unconditional support" },
    { p: "Every user has an overview of all the financings they have supported." },
    { p: "For each contribution they see:" },
    { ul: [
      "to whom they directed the funds,",
      "the gross FIAT value of their contribution,",
      "the currency of the financing,",
      "the amount of LANA actually sent,",
      "the exchange rate used,",
      "their share in the entire financing,",
      "the gross value of the repayments so far,",
      "the 3 percent fees charged,",
      "the net value they have already received,",
      "how much gross FIAT value still has to be returned to them,",
      "and the current status of the financing.",
    ] },
    { p: "The main display is always in the FIAT currency of the individual financing." },

    { h: "My unconditional financings" },
    { p: "The user also sees all the unconditional financings they have created or received." },
    { p: "For each financing they see:" },
    { ul: [
      "the desired FIAT amount,",
      "the chosen currency,",
      "the gross financed FIAT amount,",
      "the fees charged upon financing,",
      "the net FIAT value they actually received,",
      "the central fund's contribution,",
      "the contributions of community members,",
      "the number of financiers,",
      "the gross FIAT amount already returned,",
      "the remaining open FIAT value,",
      "the history of all contributions, fees, and repayments,",
      "and the option of a new repayment.",
    ] },
    { p: "If they judge that the partially collected funds are not enough for their purpose, they can return all or part of the open financed value." },

    { h: "Unconditionality and self-responsibility" },
    { p: "Unconditional financing is received with the sincere intention that the person will return the received value once their life situation allows it." },
    { p: "Repayment is not tied to:" },
    { ul: [
      "fixed monthly installments,",
      "interest,",
      "penalties,",
      "collateral,",
      "or classic creditworthiness checks.",
    ] },
    { p: "A person can return the funds gradually and according to their real capabilities." },
    { p: "If serious life circumstances arise that make it objectively impossible to return the received value, the person does not thereby become a classic debtor whom the community would punish or pursue." },
    { p: "If they truly cannot return the received value, they do not have to return it." },
    { p: "Unconditionality, however, does not mean that a person receives financing with no intention of returning it." },
    { p: "Every member approaches the financing self-responsibly and with the sincere intention of gradually returning the received value into the shared flow — through their life, their work, their projects, or the funds they receive in Lana8Wonder." },
    { p: "It means that trust, transparency, and self-responsibility replace coercion, interest, and fear." },
    { p: "The person remains more important than the open financial obligation." },

    { h: "The circulation of support" },
    { p: "When the central fund or a community member contributes to an unconditional financing, the value is actually transferred in LANA." },
    { p: "First it helps the person who needs it." },
    { p: "When that person begins returning the received value, LANA in the corresponding net FIAT value:" },
    { ul: [
      "returns to the members who trusted them,",
      "returns to the central fund,",
      "and can once again become support for the next person or project.",
    ] },
    { p: "The fees charged upon financing and upon repayment enable the development, maintenance, and long-term operation of the Unconditional Financing system." },
    { p: "In this way the same LANA helps more people over time." },
    { p: "Someone receives the community's support today. Tomorrow, through their repayment, their actions, and their contribution, they can enable support for someone else." },
    { p: "Unconditional Financing is therefore not merely a system for transferring money." },
    { p: "It is a community system in which trust, support, self-responsibility, and abundance genuinely circulate among people." },

    { h: "Further development" },
    { p: "A precise description of the individual pages, user interfaces, forms, statuses, fee accounts, and technical recording will be prepared separately, as part of the product and technical specification of the Unconditional Financing module." },
  ],
};

export default function UnconditionalFinancing() {
  const navigate = useNavigate();
  // English is the default; Slovenian only when the KIND 0 language is Slovenian.
  const sl = useLang() === "sl";
  const article = sl ? SL : EN;

  return (
    <div className="container mx-auto p-4 sm:p-6 max-w-3xl pb-24">
      <div className="flex items-center gap-3 mb-6">
        <div className="h-11 w-11 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
          <HandCoins className="h-6 w-6 text-primary" />
        </div>
        <div className="min-w-0">
          <h1 className="text-2xl sm:text-3xl font-bold leading-tight">{article.title}</h1>
          <p className="text-sm sm:text-base text-muted-foreground">{article.subtitle}</p>
        </div>
      </div>

      <Button
        className="w-full mb-6 gap-2"
        onClick={() => navigate("/unconditional-financing/requests")}
      >
        {sl ? "Poglej financiranja" : "View financings"}
        <ArrowRight className="h-4 w-4" />
      </Button>

      <Card>
        <CardContent className="p-5 sm:p-8 space-y-4 leading-relaxed">
          {article.blocks.map((block, i) => {
            if ("h" in block) {
              return (
                <h2
                  key={i}
                  className="text-lg sm:text-xl font-semibold text-foreground pt-5 mt-1 first:pt-0 first:mt-0 border-t first:border-t-0 border-border/60"
                >
                  {block.h}
                </h2>
              );
            }
            if ("ul" in block) {
              return (
                <ul key={i} className="list-disc pl-6 space-y-1.5 text-muted-foreground marker:text-primary">
                  {block.ul.map((item, j) => (
                    <li key={j} className="leading-relaxed">{item}</li>
                  ))}
                </ul>
              );
            }
            if ("ol" in block) {
              return (
                <ol
                  key={i}
                  className="list-decimal pl-6 space-y-1.5 text-muted-foreground marker:text-primary marker:font-semibold"
                >
                  {block.ol.map((item, j) => (
                    <li key={j} className="leading-relaxed">{item}</li>
                  ))}
                </ol>
              );
            }
            return (
              <p key={i} className="text-muted-foreground">
                {block.p}
              </p>
            );
          })}
        </CardContent>
      </Card>
    </div>
  );
}
